# coding: utf-8

"""
    Timepad API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import timepad
from timepad.api.webhooks_api import WebhooksApi  # noqa: E501
from timepad.rest import ApiException


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self):
        self.api = WebhooksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_hook(self):
        """Test case for add_hook

        Создать webhook для организации  # noqa: E501
        """
        pass

    def test_edit_hook(self):
        """Test case for edit_hook

        Изменить webhook  # noqa: E501
        """
        pass

    def test_get_hook(self):
        """Test case for get_hook

        Получить webhook по ID  # noqa: E501
        """
        pass

    def test_get_hooks(self):
        """Test case for get_hooks

        Получить список webhook'ов  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
