# coding: utf-8

"""
    Timepad API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import timepad
from timepad.models.payment_response import PaymentResponse  # noqa: E501
from timepad.rest import ApiException


class TestPaymentResponse(unittest.TestCase):
    """PaymentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentResponse(self):
        """Test PaymentResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = timepad.models.payment_response.PaymentResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
