# coding: utf-8

"""
    Timepad API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import timepad
from timepad.models.registration_data_response import RegistrationDataResponse  # noqa: E501
from timepad.rest import ApiException


class TestRegistrationDataResponse(unittest.TestCase):
    """RegistrationDataResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegistrationDataResponse(self):
        """Test RegistrationDataResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = timepad.models.registration_data_response.RegistrationDataResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
