# coding: utf-8

"""
    Timepad API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import timepad
from timepad.models.edit_order_status_abstract import EditOrderStatusAbstract  # noqa: E501
from timepad.rest import ApiException


class TestEditOrderStatusAbstract(unittest.TestCase):
    """EditOrderStatusAbstract unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEditOrderStatusAbstract(self):
        """Test EditOrderStatusAbstract"""
        # FIXME: construct object with mandatory attributes with example values
        # model = timepad.models.edit_order_status_abstract.EditOrderStatusAbstract()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
