# coding: utf-8

"""
    Timepad API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import timepad
from timepad.api import DefaultApi  # noqa: E501
from timepad.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_event(self):
        """Test case for add_event

        Создать событие  # noqa: E501
        """
        pass

    def test_add_order(self):
        """Test case for add_order

        Создать заказ (deprecated)  # noqa: E501
        """
        pass

    def test_add_organization(self):
        """Test case for add_organization

        Создать организацию  # noqa: E501
        """
        pass

    def test_approve_event_order(self):
        """Test case for approve_event_order

        Подтвердить заказ  # noqa: E501
        """
        pass

    def test_authorize(self):
        """Test case for authorize

        Получить токен для работы с API  # noqa: E501
        """
        pass

    def test_call_custom_method(self):
        """Test case for call_custom_method

        Вызвать кастомный метод  # noqa: E501
        """
        pass

    def test_delete_event_order(self):
        """Test case for delete_event_order

        Удалить заказ  # noqa: E501
        """
        pass

    def test_edit_event(self):
        """Test case for edit_event

        Изменить событие  # noqa: E501
        """
        pass

    def test_edit_event_order(self):
        """Test case for edit_event_order

        Изменить заказ  # noqa: E501
        """
        pass

    def test_get_event_orders(self):
        """Test case for get_event_orders

        Получить заказы события  # noqa: E501
        """
        pass

    def test_get_events(self):
        """Test case for get_events

        Получить список событий  # noqa: E501
        """
        pass

    def test_get_events_categories(self):
        """Test case for get_events_categories

        Получить список категорий событий  # noqa: E501
        """
        pass

    def test_get_events_statuses(self):
        """Test case for get_events_statuses

        Получить список статусов событий  # noqa: E501
        """
        pass

    def test_get_single_event(self):
        """Test case for get_single_event

        Получить событие по ID  # noqa: E501
        """
        pass

    def test_get_single_event_order(self):
        """Test case for get_single_event_order

        Получить заказ по ID  # noqa: E501
        """
        pass

    def test_get_tickets_statuses(self):
        """Test case for get_tickets_statuses

        Получить список статусов билетов  # noqa: E501
        """
        pass

    def test_introspect_token(self):
        """Test case for introspect_token

        Получить информацию о пользователе API  # noqa: E501
        """
        pass

    def test_introspect_token_post(self):
        """Test case for introspect_token_post

        Получить информацию о пользователе API  # noqa: E501
        """
        pass

    def test_reject_event_order(self):
        """Test case for reject_event_order

        Отклонить заказ  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
