# ref: https://docs.travis-ci.com/user/languages/python
dist: bionic
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  #- "nightly" # points to the latest development branch e.g. 3.6-dev
matrix:
  - fast_finish: true
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script:
  - pytest
