# coding: utf-8

"""
    Timepad API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class CreateHook(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'url': 'str',
        'secret': 'str',
        'type': 'str'
    }

    attribute_map = {
        'url': 'url',
        'secret': 'secret',
        'type': 'type'
    }

    def __init__(self, url=None, secret=None, type=None):  # noqa: E501
        """CreateHook - a model defined in Swagger"""  # noqa: E501
        self._url = None
        self._secret = None
        self._type = None
        self.discriminator = None
        self.url = url
        if secret is not None:
            self.secret = secret
        self.type = type

    @property
    def url(self):
        """Gets the url of this CreateHook.  # noqa: E501

        URL-адресс для колбека при событии  # noqa: E501

        :return: The url of this CreateHook.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this CreateHook.

        URL-адресс для колбека при событии  # noqa: E501

        :param url: The url of this CreateHook.  # noqa: E501
        :type: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    @property
    def secret(self):
        """Gets the secret of this CreateHook.  # noqa: E501

        Секретная фраза для подписки webhook'ов  # noqa: E501

        :return: The secret of this CreateHook.  # noqa: E501
        :rtype: str
        """
        return self._secret

    @secret.setter
    def secret(self, secret):
        """Sets the secret of this CreateHook.

        Секретная фраза для подписки webhook'ов  # noqa: E501

        :param secret: The secret of this CreateHook.  # noqa: E501
        :type: str
        """

        self._secret = secret

    @property
    def type(self):
        """Gets the type of this CreateHook.  # noqa: E501

        Тип webhook'а  # noqa: E501

        :return: The type of this CreateHook.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this CreateHook.

        Тип webhook'а  # noqa: E501

        :param type: The type of this CreateHook.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateHook, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateHook):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
