# coding: utf-8

"""
    Timepad API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class CustomMethodApiResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'success': 'bool',
        'result': 'list[CustomMethodApiResponse]'
    }

    attribute_map = {
        'success': 'success',
        'result': 'result'
    }

    def __init__(self, success=None, result=None):  # noqa: E501
        """CustomMethodApiResponse - a model defined in Swagger"""  # noqa: E501
        self._success = None
        self._result = None
        self.discriminator = None
        self.success = success
        self.result = result

    @property
    def success(self):
        """Gets the success of this CustomMethodApiResponse.  # noqa: E501

        Статус выполнения операции  # noqa: E501

        :return: The success of this CustomMethodApiResponse.  # noqa: E501
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success):
        """Sets the success of this CustomMethodApiResponse.

        Статус выполнения операции  # noqa: E501

        :param success: The success of this CustomMethodApiResponse.  # noqa: E501
        :type: bool
        """
        if success is None:
            raise ValueError("Invalid value for `success`, must not be `None`")  # noqa: E501

        self._success = success

    @property
    def result(self):
        """Gets the result of this CustomMethodApiResponse.  # noqa: E501

        Ответ кастомного метода  # noqa: E501

        :return: The result of this CustomMethodApiResponse.  # noqa: E501
        :rtype: list[CustomMethodApiResponse]
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this CustomMethodApiResponse.

        Ответ кастомного метода  # noqa: E501

        :param result: The result of this CustomMethodApiResponse.  # noqa: E501
        :type: list[CustomMethodApiResponse]
        """
        if result is None:
            raise ValueError("Invalid value for `result`, must not be `None`")  # noqa: E501

        self._result = result

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CustomMethodApiResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CustomMethodApiResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
