# coding: utf-8

"""
    Timepad API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class EditOrderAttendance(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'starts_at': 'datetime',
        'ends_at': 'datetime'
    }

    attribute_map = {
        'starts_at': 'starts_at',
        'ends_at': 'ends_at'
    }

    def __init__(self, starts_at=None, ends_at=None):  # noqa: E501
        """EditOrderAttendance - a model defined in Swagger"""  # noqa: E501
        self._starts_at = None
        self._ends_at = None
        self.discriminator = None
        if starts_at is not None:
            self.starts_at = starts_at
        if ends_at is not None:
            self.ends_at = ends_at

    @property
    def starts_at(self):
        """Gets the starts_at of this EditOrderAttendance.  # noqa: E501

        Дата посещения события  # noqa: E501

        :return: The starts_at of this EditOrderAttendance.  # noqa: E501
        :rtype: datetime
        """
        return self._starts_at

    @starts_at.setter
    def starts_at(self, starts_at):
        """Sets the starts_at of this EditOrderAttendance.

        Дата посещения события  # noqa: E501

        :param starts_at: The starts_at of this EditOrderAttendance.  # noqa: E501
        :type: datetime
        """

        self._starts_at = starts_at

    @property
    def ends_at(self):
        """Gets the ends_at of this EditOrderAttendance.  # noqa: E501

        Дата ухода с события  # noqa: E501

        :return: The ends_at of this EditOrderAttendance.  # noqa: E501
        :rtype: datetime
        """
        return self._ends_at

    @ends_at.setter
    def ends_at(self, ends_at):
        """Sets the ends_at of this EditOrderAttendance.

        Дата ухода с события  # noqa: E501

        :param ends_at: The ends_at of this EditOrderAttendance.  # noqa: E501
        :type: datetime
        """

        self._ends_at = ends_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EditOrderAttendance, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EditOrderAttendance):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
