# coding: utf-8

"""
    Timepad API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from timepad.models.edit_order_payment import EditOrderPayment  # noqa: F401,E501
from timepad.models.edit_order_visitors import EditOrderVisitors  # noqa: F401,E501


class EditOrder(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'visitors': 'list[EditOrderVisitors]',
        'answers': 'object',
        'payment': 'EditOrderPayment'
    }

    attribute_map = {
        'visitors': 'visitors',
        'answers': 'answers',
        'payment': 'payment'
    }

    def __init__(self, visitors=None, answers=None, payment=None):  # noqa: E501
        """EditOrder - a model defined in Swagger"""  # noqa: E501
        self._visitors = None
        self._answers = None
        self._payment = None
        self.discriminator = None
        if visitors is not None:
            self.visitors = visitors
        if answers is not None:
            self.answers = answers
        if payment is not None:
            self.payment = payment

    @property
    def visitors(self):
        """Gets the visitors of this EditOrder.  # noqa: E501

        Список видов билетов  # noqa: E501

        :return: The visitors of this EditOrder.  # noqa: E501
        :rtype: list[EditOrderVisitors]
        """
        return self._visitors

    @visitors.setter
    def visitors(self, visitors):
        """Sets the visitors of this EditOrder.

        Список видов билетов  # noqa: E501

        :param visitors: The visitors of this EditOrder.  # noqa: E501
        :type: list[EditOrderVisitors]
        """

        self._visitors = visitors

    @property
    def answers(self):
        """Gets the answers of this EditOrder.  # noqa: E501

        Ответы на анкету регистрации  # noqa: E501

        :return: The answers of this EditOrder.  # noqa: E501
        :rtype: object
        """
        return self._answers

    @answers.setter
    def answers(self, answers):
        """Sets the answers of this EditOrder.

        Ответы на анкету регистрации  # noqa: E501

        :param answers: The answers of this EditOrder.  # noqa: E501
        :type: object
        """

        self._answers = answers

    @property
    def payment(self):
        """Gets the payment of this EditOrder.  # noqa: E501


        :return: The payment of this EditOrder.  # noqa: E501
        :rtype: EditOrderPayment
        """
        return self._payment

    @payment.setter
    def payment(self, payment):
        """Sets the payment of this EditOrder.


        :param payment: The payment of this EditOrder.  # noqa: E501
        :type: EditOrderPayment
        """

        self._payment = payment

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EditOrder, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EditOrder):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
