# coding: utf-8

"""
    Timepad API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ImageResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'default_url': 'str',
        'uploadcare_url': 'str'
    }

    attribute_map = {
        'default_url': 'default_url',
        'uploadcare_url': 'uploadcare_url'
    }

    def __init__(self, default_url=None, uploadcare_url=None):  # noqa: E501
        """ImageResponse - a model defined in Swagger"""  # noqa: E501
        self._default_url = None
        self._uploadcare_url = None
        self.discriminator = None
        self.default_url = default_url
        self.uploadcare_url = uploadcare_url

    @property
    def default_url(self):
        """Gets the default_url of this ImageResponse.  # noqa: E501

        Картинка стандартного размера  # noqa: E501

        :return: The default_url of this ImageResponse.  # noqa: E501
        :rtype: str
        """
        return self._default_url

    @default_url.setter
    def default_url(self, default_url):
        """Sets the default_url of this ImageResponse.

        Картинка стандартного размера  # noqa: E501

        :param default_url: The default_url of this ImageResponse.  # noqa: E501
        :type: str
        """
        if default_url is None:
            raise ValueError("Invalid value for `default_url`, must not be `None`")  # noqa: E501

        self._default_url = default_url

    @property
    def uploadcare_url(self):
        """Gets the uploadcare_url of this ImageResponse.  # noqa: E501

        Адрес картинки на uploadcare, к которому можно прибавлять запросы в формате uploadcare  # noqa: E501

        :return: The uploadcare_url of this ImageResponse.  # noqa: E501
        :rtype: str
        """
        return self._uploadcare_url

    @uploadcare_url.setter
    def uploadcare_url(self, uploadcare_url):
        """Sets the uploadcare_url of this ImageResponse.

        Адрес картинки на uploadcare, к которому можно прибавлять запросы в формате uploadcare  # noqa: E501

        :param uploadcare_url: The uploadcare_url of this ImageResponse.  # noqa: E501
        :type: str
        """
        if uploadcare_url is None:
            raise ValueError("Invalid value for `uploadcare_url`, must not be `None`")  # noqa: E501

        self._uploadcare_url = uploadcare_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImageResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImageResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
