# coding: utf-8

"""
    Timepad API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Link(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'title': 'str',
        'href': 'str',
        'templated': 'bool'
    }

    attribute_map = {
        'name': 'name',
        'title': 'title',
        'href': 'href',
        'templated': 'templated'
    }

    def __init__(self, name=None, title=None, href=None, templated=None):  # noqa: E501
        """Link - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._title = None
        self._href = None
        self._templated = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if title is not None:
            self.title = title
        if href is not None:
            self.href = href
        if templated is not None:
            self.templated = templated

    @property
    def name(self):
        """Gets the name of this Link.  # noqa: E501

        Машиночитаемое описание ссылки (для оплат - строковый идентификатор платёжной системы)  # noqa: E501

        :return: The name of this Link.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Link.

        Машиночитаемое описание ссылки (для оплат - строковый идентификатор платёжной системы)  # noqa: E501

        :param name: The name of this Link.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def title(self):
        """Gets the title of this Link.  # noqa: E501

        Человекочитаемое описание ссылки (для оплат - название платёжной системы)  # noqa: E501

        :return: The title of this Link.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Link.

        Человекочитаемое описание ссылки (для оплат - название платёжной системы)  # noqa: E501

        :param title: The title of this Link.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def href(self):
        """Gets the href of this Link.  # noqa: E501

        Ссылка  # noqa: E501

        :return: The href of this Link.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this Link.

        Ссылка  # noqa: E501

        :param href: The href of this Link.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def templated(self):
        """Gets the templated of this Link.  # noqa: E501

        Признак того, что ссылка - шаблон. У curies - true, в остальных случаях не присутствует  # noqa: E501

        :return: The templated of this Link.  # noqa: E501
        :rtype: bool
        """
        return self._templated

    @templated.setter
    def templated(self, templated):
        """Sets the templated of this Link.

        Признак того, что ссылка - шаблон. У curies - true, в остальных случаях не присутствует  # noqa: E501

        :param templated: The templated of this Link.  # noqa: E501
        :type: bool
        """

        self._templated = templated

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Link, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Link):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
