# coding: utf-8

"""
    Timepad API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TicketTypeRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'price': 'int',
        'status': 'str',
        'name': 'str',
        'description': 'str',
        'sale_starts_at': 'datetime',
        'sale_ends_at': 'datetime',
        'send_personal_links': 'bool',
        'limit': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'price': 'price',
        'status': 'status',
        'name': 'name',
        'description': 'description',
        'sale_starts_at': 'sale_starts_at',
        'sale_ends_at': 'sale_ends_at',
        'send_personal_links': 'send_personal_links',
        'limit': 'limit'
    }

    def __init__(self, id=None, price=None, status=None, name=None, description=None, sale_starts_at=None, sale_ends_at=None, send_personal_links=None, limit=None):  # noqa: E501
        """TicketTypeRequest - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._price = None
        self._status = None
        self._name = None
        self._description = None
        self._sale_starts_at = None
        self._sale_ends_at = None
        self._send_personal_links = None
        self._limit = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if price is not None:
            self.price = price
        if status is not None:
            self.status = status
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if sale_starts_at is not None:
            self.sale_starts_at = sale_starts_at
        if sale_ends_at is not None:
            self.sale_ends_at = sale_ends_at
        if send_personal_links is not None:
            self.send_personal_links = send_personal_links
        if limit is not None:
            self.limit = limit

    @property
    def id(self):
        """Gets the id of this TicketTypeRequest.  # noqa: E501

        Номер существующего типа билета  # noqa: E501

        :return: The id of this TicketTypeRequest.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TicketTypeRequest.

        Номер существующего типа билета  # noqa: E501

        :param id: The id of this TicketTypeRequest.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def price(self):
        """Gets the price of this TicketTypeRequest.  # noqa: E501

        Цена существующего типа билета  # noqa: E501

        :return: The price of this TicketTypeRequest.  # noqa: E501
        :rtype: int
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this TicketTypeRequest.

        Цена существующего типа билета  # noqa: E501

        :param price: The price of this TicketTypeRequest.  # noqa: E501
        :type: int
        """

        self._price = price

    @property
    def status(self):
        """Gets the status of this TicketTypeRequest.  # noqa: E501

        Статус типа билета  # noqa: E501

        :return: The status of this TicketTypeRequest.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this TicketTypeRequest.

        Статус типа билета  # noqa: E501

        :param status: The status of this TicketTypeRequest.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def name(self):
        """Gets the name of this TicketTypeRequest.  # noqa: E501

        Название типа билета  # noqa: E501

        :return: The name of this TicketTypeRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TicketTypeRequest.

        Название типа билета  # noqa: E501

        :param name: The name of this TicketTypeRequest.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this TicketTypeRequest.  # noqa: E501

        Описание типа билета  # noqa: E501

        :return: The description of this TicketTypeRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this TicketTypeRequest.

        Описание типа билета  # noqa: E501

        :param description: The description of this TicketTypeRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def sale_starts_at(self):
        """Gets the sale_starts_at of this TicketTypeRequest.  # noqa: E501

        Дата начала продажи типа билета  # noqa: E501

        :return: The sale_starts_at of this TicketTypeRequest.  # noqa: E501
        :rtype: datetime
        """
        return self._sale_starts_at

    @sale_starts_at.setter
    def sale_starts_at(self, sale_starts_at):
        """Sets the sale_starts_at of this TicketTypeRequest.

        Дата начала продажи типа билета  # noqa: E501

        :param sale_starts_at: The sale_starts_at of this TicketTypeRequest.  # noqa: E501
        :type: datetime
        """

        self._sale_starts_at = sale_starts_at

    @property
    def sale_ends_at(self):
        """Gets the sale_ends_at of this TicketTypeRequest.  # noqa: E501

        Дата окончания продажи типа билета  # noqa: E501

        :return: The sale_ends_at of this TicketTypeRequest.  # noqa: E501
        :rtype: datetime
        """
        return self._sale_ends_at

    @sale_ends_at.setter
    def sale_ends_at(self, sale_ends_at):
        """Sets the sale_ends_at of this TicketTypeRequest.

        Дата окончания продажи типа билета  # noqa: E501

        :param sale_ends_at: The sale_ends_at of this TicketTypeRequest.  # noqa: E501
        :type: datetime
        """

        self._sale_ends_at = sale_ends_at

    @property
    def send_personal_links(self):
        """Gets the send_personal_links of this TicketTypeRequest.  # noqa: E501

        Категория билетов с отправкой персональных ссылок  # noqa: E501

        :return: The send_personal_links of this TicketTypeRequest.  # noqa: E501
        :rtype: bool
        """
        return self._send_personal_links

    @send_personal_links.setter
    def send_personal_links(self, send_personal_links):
        """Sets the send_personal_links of this TicketTypeRequest.

        Категория билетов с отправкой персональных ссылок  # noqa: E501

        :param send_personal_links: The send_personal_links of this TicketTypeRequest.  # noqa: E501
        :type: bool
        """

        self._send_personal_links = send_personal_links

    @property
    def limit(self):
        """Gets the limit of this TicketTypeRequest.  # noqa: E501

        Ограничение на количество билетов этого типа  # noqa: E501

        :return: The limit of this TicketTypeRequest.  # noqa: E501
        :rtype: bool
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this TicketTypeRequest.

        Ограничение на количество билетов этого типа  # noqa: E501

        :param limit: The limit of this TicketTypeRequest.  # noqa: E501
        :type: bool
        """

        self._limit = limit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TicketTypeRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TicketTypeRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
