# coding: utf-8

"""
    Timepad API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TicketInclude(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'answers': 'object',
        'ticket_type_id': 'str'
    }

    attribute_map = {
        'answers': 'answers',
        'ticket_type_id': 'ticket_type_id'
    }

    def __init__(self, answers=None, ticket_type_id=None):  # noqa: E501
        """TicketInclude - a model defined in Swagger"""  # noqa: E501
        self._answers = None
        self._ticket_type_id = None
        self.discriminator = None
        if answers is not None:
            self.answers = answers
        self.ticket_type_id = ticket_type_id

    @property
    def answers(self):
        """Gets the answers of this TicketInclude.  # noqa: E501

        Ответы на анкету регистрации  # noqa: E501

        :return: The answers of this TicketInclude.  # noqa: E501
        :rtype: object
        """
        return self._answers

    @answers.setter
    def answers(self, answers):
        """Sets the answers of this TicketInclude.

        Ответы на анкету регистрации  # noqa: E501

        :param answers: The answers of this TicketInclude.  # noqa: E501
        :type: object
        """

        self._answers = answers

    @property
    def ticket_type_id(self):
        """Gets the ticket_type_id of this TicketInclude.  # noqa: E501

        Номер типа билета  # noqa: E501

        :return: The ticket_type_id of this TicketInclude.  # noqa: E501
        :rtype: str
        """
        return self._ticket_type_id

    @ticket_type_id.setter
    def ticket_type_id(self, ticket_type_id):
        """Sets the ticket_type_id of this TicketInclude.

        Номер типа билета  # noqa: E501

        :param ticket_type_id: The ticket_type_id of this TicketInclude.  # noqa: E501
        :type: str
        """
        if ticket_type_id is None:
            raise ValueError("Invalid value for `ticket_type_id`, must not be `None`")  # noqa: E501

        self._ticket_type_id = ticket_type_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TicketInclude, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TicketInclude):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
