# coding: utf-8

"""
    Timepad API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class WidgetResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code_html': 'str'
    }

    attribute_map = {
        'code_html': 'code_html'
    }

    def __init__(self, code_html=None):  # noqa: E501
        """WidgetResponse - a model defined in Swagger"""  # noqa: E501
        self._code_html = None
        self.discriminator = None
        self.code_html = code_html

    @property
    def code_html(self):
        """Gets the code_html of this WidgetResponse.  # noqa: E501

        Код вставки виджета в сайт  # noqa: E501

        :return: The code_html of this WidgetResponse.  # noqa: E501
        :rtype: str
        """
        return self._code_html

    @code_html.setter
    def code_html(self, code_html):
        """Sets the code_html of this WidgetResponse.

        Код вставки виджета в сайт  # noqa: E501

        :param code_html: The code_html of this WidgetResponse.  # noqa: E501
        :type: str
        """
        if code_html is None:
            raise ValueError("Invalid value for `code_html`, must not be `None`")  # noqa: E501

        self._code_html = code_html

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WidgetResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WidgetResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
