# coding: utf-8

"""
    Timepad API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class WidgetContainterInclude(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'custom': 'str',
        'button': 'str'
    }

    attribute_map = {
        'custom': 'custom',
        'button': 'button'
    }

    def __init__(self, custom=None, button=None):  # noqa: E501
        """WidgetContainterInclude - a model defined in Swagger"""  # noqa: E501
        self._custom = None
        self._button = None
        self.discriminator = None
        self.custom = custom
        self.button = button

    @property
    def custom(self):
        """Gets the custom of this WidgetContainterInclude.  # noqa: E501

        Код вставки виджета в сайт  # noqa: E501

        :return: The custom of this WidgetContainterInclude.  # noqa: E501
        :rtype: str
        """
        return self._custom

    @custom.setter
    def custom(self, custom):
        """Sets the custom of this WidgetContainterInclude.

        Код вставки виджета в сайт  # noqa: E501

        :param custom: The custom of this WidgetContainterInclude.  # noqa: E501
        :type: str
        """
        if custom is None:
            raise ValueError("Invalid value for `custom`, must not be `None`")  # noqa: E501

        self._custom = custom

    @property
    def button(self):
        """Gets the button of this WidgetContainterInclude.  # noqa: E501

        Код виджета-кнопки для вставки на сайт  # noqa: E501

        :return: The button of this WidgetContainterInclude.  # noqa: E501
        :rtype: str
        """
        return self._button

    @button.setter
    def button(self, button):
        """Sets the button of this WidgetContainterInclude.

        Код виджета-кнопки для вставки на сайт  # noqa: E501

        :param button: The button of this WidgetContainterInclude.  # noqa: E501
        :type: str
        """
        if button is None:
            raise ValueError("Invalid value for `button`, must not be `None`")  # noqa: E501

        self._button = button

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WidgetContainterInclude, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WidgetContainterInclude):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
